booking_hotel/urls.py
from django.urls import path
from . import views

app_name = 'booking_hotel'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hotel_id>/', views.book_now, name = "book_now"),
    path('<int:hotel_id>/process', views.book_process, name = "book_process"),
]

bookinghotel/urls.py
from django.urls import path
from .views import booking_hotel

urlpatterns = [
    path('', booking_hotel, name="booking"),
]

citizi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('booking/', include('bookinghotel.urls')),
    path('book_hotel/', include('booking_hotel.urls')),
    path('add_hotel/', include('add_hotel.urls')),
]

booking_hotel/models.py
from django.db import models
from datetime import datetime, date
from django.utils import timezone
from add_hotel.models import Hotel

class Booking(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length = 27, default = "User")
    check_in = models.DateField()
    check_out = models.DateField()
    guests = models.PositiveIntegerField()
    def __str__(self):
        return self.hotel.hotel_name + " " + self.check_in.strftime('%Y-%m-%d') + " " + self.check_out.strftime('%Y-%m-%d')

bookinghotel/models.py
from django.db import models

# Create your models here.


class SearchHotel(models.Model):
    id_search = models.CharField(max_length=50)

booking_hotel/forms.py
from .models import Booking
from django import forms
import datetime
from django.core.exceptions import ValidationError

class BookingForm(forms.Form):

    customer_name = forms.CharField(label = "On Behalf Of", required = True, max_length=27, widget = forms.TextInput(
        attrs = {
            'class': 'form-control form-booking',
            'placeholder': 'Your Name'
        }
    ))

    check_in = forms.DateField(required = True, widget = forms.DateInput(
        attrs = {
            'class': 'form-control form-booking',
            'type' : 'date',
            'placeholder': 'Date in'
            
        }
    ))

    check_out = forms.DateField(required = True, widget = forms.DateInput(
        attrs = {
            'class': 'form-control form-booking',
            'type' : 'date',
            'placeholder': 'Date out'
        }
    ))
    
    guests = forms.CharField(label = "guests", required = True, max_length=27, widget = forms.TextInput(
        attrs = {
            'class': 'form-control form-booking',
            'type' : 'number',
            'placeholder': 'total people'
        }
    ))

    class Meta:
        model = Booking
        fields = ['customer-name', 'check_in', 'check-out', 'guests']

    def clean(self):
        check_in = self.cleaned_data['check_in']
        check_out = self.cleaned_data['check_out']
        
        if check_in == check_out:
             self.add_error('check_out', 'order hotel Min. 1 day')
        if check_out < check_in:
            self.add_error('check_out', "check out should be on future")
        if check_in < datetime.date.today():
             self.add_error('check_out', 'check in minimal from today')
        
        return check_in

bookinghotel/forms.py
from django import forms
from .models import SearchHotel


class SearchHotelForm(forms.Form):
    id_search = forms.CharField(max_length=50, required=True)

booking_hotel/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .forms import BookingForm
from .models import Booking
from add_hotel.models import Hotel
from django.views.decorators.csrf import csrf_protect

response = {}

def book_now(request, hotel_id):
    hotel = get_object_or_404(Hotel, pk = hotel_id)
    response['hotel'] = hotel
    response['BookingForm'] = BookingForm
    response['isFilled'] = ""
    return render(request, 'booking_hotel/book_hotel_detail.html', response)

@csrf_protect
def book_process(request, hotel_id):
    form = BookingForm(request.POST or None)
    hotel = get_object_or_404(Hotel, pk = hotel_id)
    response['hotel'] = hotel
    if request.method == 'POST' and form.is_valid():
        booking = Booking(hotel = hotel,
        customer_name = request.POST['customer_name'],
        check_in = request.POST['check_in'],
        check_out = request.POST['check_out'],
        guests = request.POST['guests'])
        booking.save()
        return HttpResponseRedirect('/booking/')
    else:
        response['BookingForm'] = form
        return render (request, 'booking_hotel/book_hotel_detail.html', response)

def index():
    return HttpResponse("haihai")

bookinghotel/views.py
from django.shortcuts import render, redirect
from add_hotel.models import Hotel
from .models import SearchHotel
from .forms import SearchHotelForm

# Create your views here.


def booking_hotel(request):
    if request.method == 'POST':
        form = SearchHotelForm(request.POST)
        if form.is_valid():
            id_search = request.POST['id_search']
            hotel_by_city = Hotel.objects.filter(city=id_search)
            return render(request, 'bookinghotel.html', {
                'hotel_by_city': hotel_by_city
            })
    return render(request, "bookinghotel.html")

booking_hotel/templates/booking_hotel/book_hotel_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Citizi | Book Hotel{% endblock %}
{% block style %}
<link href="{% static 'booking_hotel/booking_hotel.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
{% include 'navbar.html' %}

    <div class="jumbo-book bg-primary text-white  p-5">    
        <div class = >
            <a href="/booking/">
                <b class = "back"> < </b>
            </a>
            <b>Booking Details</b>
        </div>
        <div class = "down d-flex align-items-end p-4">
            <div>
                <h1 class = "ml-3 mb-2"><b>{{ hotel.hotel_name }}</b></h1>
                <div class="d-flex justify-content-start ml-3 mb-2 mt-4">
                    <img class = "pb-2 mr-2" src="{% static 'booking_hotel/location.svg' %}" alt="">
                    <h6>{{ hotel.address }}, {{ hotel.city }} </h6>
                </div>
            </div>
        </div>
    </div>

    <form action="{% url 'booking_hotel:book_process' hotel.id %}" method="POST">
        {% csrf_token %}
            <div class="row m-2 justify-content-center">
                <div class="col-sm-2  col-xs-12 d-flex justify-content-center">
                    <img class = "form-icon" src="{% static 'booking_hotel/people.svg' %}" alt="">
                </div>
                <div class="col-sm-5 form-group col-xs-12">
                    <label for="{{BookingForm.customer_name.id_for_label}}" class=form-label>{{BookingForm.customer_name.label}}</label>
                    {% csrf_token %}
                    {{ BookingForm.customer_name }}                
                </div>
                <div class="col-sm-5 col-xs-12 form-group">
                    <label for="{{BookingForm.guests.id_for_label}}" class=form-label>{{BookingForm.guests.label}}</label>
                    {% csrf_token %}
                    {{ BookingForm.guests }}
                </div>
            </div>
            <div class="row m-2 justify-content-center mt-3">
                <div class="col-sm-2  col-xs-12 d-flex justify-content-center">
                    <img class = "form-icon" src="{% static 'booking_hotel/calendar.svg' %}" alt="">
                </div>
                <div class="col-sm-5 form-group col-xs-12">
                    <label for="{{BookingForm.check_in.id_for_label}}" class=form-label>{{BookingForm.check_in.label}}</label>
                    {% csrf_token %}
                    {{ BookingForm.check_in }}
                </div>
                <div class="col-sm-5 col-xs-12 form-group">
                    <label for="{{BookingForm.check_out.id_for_label}}" class=form-label>{{BookingForm.check_out.label}}</label>
                    {% csrf_token %}
                    {{ BookingForm.check_out }}
                </div>
            </div>

            {% for item in BookingForm %}
                {% if item.errors %}
                    {{ item.errors }}
                {% endif %}
            {% endfor %}

            <div class="d-flex justify-content-end m-5">
                <div class="button-container">
                    <input class="button-container primary-button" type="submit" name="submit" value="Book now">
                </div>
            </div>

    </form>

{% endblock %}