add_hotel/urls.py
from django.urls import path
from . import views

app_name = 'add_hotel'

urlpatterns = [
    path('', views.addHotel, name="addHotel"),
]

citizi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('booking/', include('bookinghotel.urls')),
    path('book_hotel/', include('booking_hotel.urls')),
    path('add_hotel/', include('add_hotel.urls')),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
	path('secret/', views.placeholder, name="placeholder"),
	path('', views.crowdTracker, name="crowdTracker"),
	path('display/', views.displayByCity, name="displayByCity"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Citizi{% endblock %}</title>

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700|Roboto:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block style %}{% endblock %}
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 18px;
            height: 100vh;
            width: 100vw;
        }

        body {
            font-family: 'Raleway', sans-serif;
            scroll-behavior: smooth;
        }

        section {
            width: 100vw;
            min-height: 100vh;
        }
    </style>

</head>

<body style="overflow-x: hidden; {% block bodyline %}{% endblock %}" class="{% block class %}{% endblock %}">

    {% block content %}
    <h1>Hello World!</h1>
    {% endblock %}

    {% block script %}{% endblock %}
</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">

	<a class="navbar-brand" href="#">Citizi</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Menu-bar">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="Menu-bar">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'mainapp:crowdTracker' %}">Crowd Tracker</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/booking/">Book Hotel</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'add_hotel:addHotel' %}">Add Hotel</a>
			</li>
		</ul>
	</div>
</nav>